### ISSUE TITLE
Change date string parsing

### ISSUE THREAD

**Issue by josteinl** [emerald-geomodelling/libsgfdata#16]
We have started using your library in one of our projects and it is very good.

We have encountered a problem with the date parsing, though. 

Dates on the format `HD=20120105` will result in `datetime.date(2021, 05, 01)`. I would expect that if the first part is the year, then it is followed by month and day.

I understand that it is impossible to always interpret the date strings correctly.

Are you willing to accept a pull request for this issue?

Again, thank you for a very nice library.

**Comment by redhog** [comment]
Heyas!

Thank you :)

IMHO, date string parsing should always prefer Scandinavian date formats over American when a date can be interpreted as both, as after all, SGF is the _Swedish_ geotehcnical institute. HD=20210105  -> datetime.date(2021, 05, 01) is a bug in my opinion.

I have to admit I thought this was already working this way, given the `dayfirst=True` in this code used to parse dates:

`dateutil.parser.parse(v, parserinfo=dateutil.parser.parserinfo(dayfirst=True)).date()`

When I try it on the command line it seems to indeed work correctly:
```
>>> import dateutil.parser
>>> dateutil.parser.parse("20120105", parserinfo=dateutil.parser.parserinfo(dayfirst=True)).date()
datetime.date(2012, 5, 1)
```

I'd be happy to receive a PR!

**Comment by josteinl** [comment]
Hello again

Just to clarify: Do you mean it is correct to interpret the date string `20210105` as `datetime.date(2021, 5, 1)`? I understand it is how it works today, but that is what I find problematic. 

I agree if the year is the last part of the date string, the day comes before the month in Scandinavia, but if the year comes first, then the string should be interpreted as an ISO-8601 (YYYY-MM-DD) date string.

Please advice.

**Comment by josteinl** [comment]
Just another factor, that I just discovered:

![image](https://user-images.githubusercontent.com/9363084/135593010-ad1b90c6-d1b4-48fe-b602-8c2f01442bb2.png)

The specification says the date format should be in ISO-8601.

**Comment by redhog** [comment]
Oh... I'm apparently blind today! ;S

20210105 really should mean datetime.date(2021, 1, 5)... I guess dayfirst=True doesn't work with YYYYMMDD (and only solves DDMMYYYY vs MMDDYYYY)... So yes, if you have a solution for this I'd be happy to merge it!

Yes, the format "should" be YYMMDD, but in real life data I have come across (mostly files downloaded from NADAG), KD and RefDatum are seldom in a proper format - I guess because they're typically not automatically filled in but entered by a human as a text field...

**Comment by redhog** [comment]
```
>>> dateutil.parser.parse("20120105", parserinfo=dateutil.parser.parserinfo(dayfirst=False)).date()
datetime.date(2012, 1, 5)
>>> dateutil.parser.parse("05012012", parserinfo=dateutil.parser.parserinfo(dayfirst=False)).date()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/redhog/Projects/Emerald/EmeraldInterpret/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1356, in parse
    return parser(parserinfo).parse(timestr, **kwargs)
  File "/home/redhog/Projects/Emerald/EmeraldInterpret/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 654, in parse
    ret = self._build_naive(res, default)
  File "/home/redhog/Projects/Emerald/EmeraldInterpret/env/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1229, in _build_naive
    naive = default.replace(**repl)
ValueError: month must be in 1..12
>>> dateutil.parser.parse("05012012", parserinfo=dateutil.parser.parserinfo(dayfirst=True)).date()
datetime.date(501, 12, 20)

```

So I'm not sure how any of this ever worked properly :(

**Comment by redhog** [comment]
```
>>> dateutil.parser.parse("05-01-2012", parserinfo=dateutil.parser.parserinfo(dayfirst=False)).date()
datetime.date(2012, 5, 1)
>>> dateutil.parser.parse("05-01-2012", parserinfo=dateutil.parser.parserinfo(dayfirst=True)).date()
datetime.date(2012, 1, 5)
>>> dateutil.parser.parse("2012-01-05", parserinfo=dateutil.parser.parserinfo(dayfirst=True)).date()
datetime.date(2012, 5, 1)
>>> dateutil.parser.parse("2012-01-05", parserinfo=dateutil.parser.parserinfo(dayfirst=False)).date()
datetime.date(2012, 1, 5)
```
