### ISSUE TITLE
Strip spaces?

### ISSUE THREAD

**Issue by josteinl** [emerald-geomodelling/libsgfdata#19]
What is your position on removing leading and trailing spaces from field values? 

In some of our files we get headers (method header) like this:

```
£
IG= ,FiPos=2,FiLiq=,FiTyp=,IE=0.844,<--snip-->
#

``` 

The `IG` code is defined as the application class (användningsklass) and should be an integer in the range [1-4], and the specification also says that you should specify 0 if another class is used(?!). So the actual range is [0-4]. Anyway, the problem is that the space character results in an exception:

```
Exception
could not convert string to float: '': IG= ,FiPos=2,FiLiq=,FiTyp=,IE=0.844,<--snip-->
``` 

I would consider this value as an error that should be ignored, rather than raise an exception.

Another case is a method data line with a trailing space:

```
D=15.825,A=0.471,<--snip-->,R=0,K=90,T=Avbruten utan stopp 
```

The data `T=Avbruten utan stopp ` has a trailing space that I would like to remove.

I would submit a PR if you think it is OK to strip leading and trailing spaces from the data.

**Comment by redhog** [comment]
Regarding IG (and other numerical fields):

_RE_FLOAT already allows space on either side of the numerical value, and e.g. _conv(" 123    ") returns 123. The problem in your case is that the value is " ", which doesn't contain a number at all still matches _RE_FLOAT. The is a bug: you should have been left with a field containing a one-space string... If you have a bugfix for _RE_FLOAT / _RE_INT I'd be happy to merge it :)

As for pure string fields, like your T comment, I'm in two minds about stripping spaces in the library itself. On the one hand, these are fields entered by humans, and humans make mistakes like adding trailing spaces. On the other hand, these are humanly entered values with no known semantic, so assuming stuff about the content is a bit dangerous...

I'm planning to make a "normalization" function / set of functions (see Ed's ticket https://github.com/emerald-geomodelling/libsgfdata/issues/15) and this could easily do this kind of transformation too. Would this be good enough for your usage?
