### ISSUE TITLE
Overview ticket: Preliminary testing and bugfixes 

### ISSUE THREAD

**Issue by Duke-of-Lizard** [emerald-geomodelling/libsgfdata#2]
I'm testing this out for the first time on real data from Norway, and I'm noting down my finding in this ticket where we can discuss possible fixes. I summarise in this first comment:

- [x] behaviour of headers split over multiple columns
- [x] method codes for CPT are 7 when parsing example files
- [x] possible typos of english field names?
- [x] date formats not consistent.... possible solutions? 
- [x] determine if "%"-delimited field in 1059.cpt is an error in the file that is non-SGF-format compliant, or is this something in the file format specification that we have missed?

**Comment by Duke-of-Lizard** [comment]
![image](https://user-images.githubusercontent.com/61405744/128490870-84e96edd-77ae-437b-91c5-bbed1ac64a2c.png)

**Comment by Duke-of-Lizard** [comment]
I've added example data and a jupyter notebook. Some of my first findings: 

The file **examples/data/1059.cpt** has the header split over two lines. This gets split into two seperate dictionary. Was this intentional? 
![image](https://user-images.githubusercontent.com/61405744/128491214-a4dcb2a9-9fc5-4f06-a300-17dadfe2f44b.png)
![image](https://user-images.githubusercontent.com/61405744/128491073-ff8f68a0-1ae3-4472-8044-fa05e2918523.png)

- While total soundings and rotary pressure soundings have their method codes converted to an english plaintext code, CPT soundings still have a number. (It seems to be the same 7 that GeoSuite databases use.) 
![image](https://user-images.githubusercontent.com/61405744/128492458-cd173830-9185-4287-bd0d-f339f65382fd.png)

-

**Comment by Duke-of-Lizard** [comment]
I want to discuss these findings with @redhog before I proceed to implement changes. I'm filing this ticket under the "blocked" column until then.

**Comment by redhog** [comment]
I've added example data and a jupyter notebook. Some of my first findings:
  
  The file examples/data/1059.cpt has the header split over two lines. This gets split into two seperate dictionary. Was this intentional?
  
yep :) This is as per the standard.. What this is supposed to _mean_ is another thing.

**Comment by redhog** [comment]
Some of these wierd names are not exactly SGF, but an extension from [Geotech
AB](https://static1.squarespace.com/static/565c5cc1e4b05079e4c0fcfb/t/587c984bbf629abac09d265f/1484560476906/6-SWE-CPT-LOG-v5.xx.pdf), see https://github.com/emerald-geomodelling/libsgfdata/commit/4a7ae4e4f08b3e42a0bd7efc2d89d209679cafc0

**Comment by redhog** [comment]
As for dates/times, they're not actually currently parsed (any more than pandas read_csv does by itself), and I'm a bit unsure if formats are followed. Moreover there are multiple date fields, with different formats:

In main.csv:
* RefDatum,Date Reference measurement,,figure (YYYYMMDD),
* Geotech AB ext: HD,"Datum för undersökning",,,
  
In data.csv:
* AD,Time,seconds,figure,
* DatumTid,Measured value’s time indication,yyyymmddhhmmssmsmsms,,
* Geotech AB ext: %,Tidsangivelse för lagrad mätdata,,,

Maybe some of these should be collapsed (the Geotech AB extensions converted to their standard equivalent)?

**Comment by redhog** [comment]
As for 1059.cpt, I'd say that's correctly parsed, given the spec. What's it supposed to mean / do you know what the file's supposed to contain?

**Comment by redhog** [comment]
Re misspellings: Most names are copied from the pdf spec verbatim... Not sure how it ended up wrong? But easy to fix, they're all in the CSV:s inside the library. Feel free to fix :)
