### ISSUE TITLE
Real-world data with method block code in main block

### ISSUE THREAD

**Issue by josteinl** [emerald-geomodelling/libsgfdata#34]
We get lots of total soundings files that contain the `HI` code in the main block ($):

```
$
HD=20210324,HI=004940,HM=24
#
D=0.025,A=1.096
D=0.050,A=1.096
D=0.075,A=1.096
...
```

In the SGF standard, the `HI` code is only defined for the method block (€ or £). 

Our problem is that this code `HI` (undefined for the main block) is returned as an integer (4940) that sort of garbles the data for us (leading zeros removed).

A solution for us is to add the `HI` code to the `/libsgfdata/main.csv` and also add a converter function for this time string.  

I am trying to get a name for the source of these files so they also can be added to the main code file.

Do you think this is something you would accept a PR for?

**Comment by redhog** [comment]
Most definitely - but please add a sensible name for the source if possible. If not, use your own organization, but that should really be a last resort imo...

**Comment by josteinl** [comment]
I got reported that this file was generated by a drill rig Geotech 605. So I assume this adds to the `geotechab` source in the `/libsgfdata/main.csv`.

Yes, this adds to the KD (date). The HI code is the time of day. The example above is at the time `00:49:40`.

I'll submit a PR before noon.

I'm not sure about what the normalization function does. Maybe you could guide me if something is missing in the PR?

**Comment by redhog** [comment]
Ah, correct normalization is AD, not KD :)
